# -*- coding: utf-8 -*-
"""csv_handler

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhaoIQP5RyGVvqXVOVkchG-hDDQuz1Qa
"""

import os
import csv

def append_data_to_csv(data, file_name='results.csv', headers=None):
    if headers is None:
        headers = ['Connmodel_Acc', 'Connmodel_MCC', 'Connmodel_F1',
                   'XGBoost_Acc', 'XGBoost_MCC', 'XGBoost_F1',
                   'AutoML_Acc', 'AutoML_MCC', 'AutoML_F1',
                   'TabNet_Acc', 'TabNet_MCC', 'TabNet_F1']

    file_exists = os.path.isfile(file_name)

    with open(file_name, 'a', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=headers)
        if not file_exists:
            writer.writeheader()
        writer.writerow(data)